name: CI - Build & Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        # 커밋 SHA 태그 빌드
        docker build -t wonilinfra/soloud:${{ github.sha }} .
        # latest 태그도 추가
        docker tag wonilinfra/soloud:${{ github.sha }} wonilinfra/soloud:latest

    - name: Push to Docker Hub
      run: |
        # 둘 다 푸시
        docker push wonilinfra/soloud:${{ github.sha }}
        docker push wonilinfra/soloud:latest

